################################################################################
#
# Build for module files.
# Copyright (c) 2020-2023
# Original Author: 1107473010@qq.com
#
################################################################################
obj-m := kernel_nvmem.o
FIRMWARE_CLEAN := 1

include $(AGENT_PLATFORM_SOC_PATH)/mod_driverbuildmod.mk