################################################################################
#
# Build for module files.
# Copyright (c) 2020-2023
# Original Author: 1107473010@qq.com
#
################################################################################
obj-m := goodix_ts_i2c.o
FIRMWARE_CLEAN := 1

include $(AGENT_PLATFORM_SOC_PATH)/mod_driver/buildmod.mk