################################################################################
#
# Build for module files.
# Copyright (c) 2020-2023
# Original Author: 1107473010@qq.com
#
################################################################################
BUILD = e

c_objects = st7789_fb_test.o

buildout = st7789_fb_test

include $(AGENT_PLATFORM_SOC_PATH)/mod_driver/buildrules.mk
