################################################################################
#
# Build for module files.
# Copyright (c) 2020-2023
# Original Author: 1107473010@qq.com
#
################################################################################
BUILD =e

c_objects = icm_spi_test.o

# This is the file name of the executables and path where 
# place the executables
buildout = icm_spi_test

include $(AGENT_PLATFORM_SOC_PATH)/mod_driver/buildrules.mk